### PR TITLE
Add template

### PR DESCRIPTION
**Pull request by yaacov**
Templates are fun.

**create**:
`oc process -p PATCH=5490 -f template.yaml | oc create -f -`

**delete:**
`oc process -p PATCH=5490 -f template.yaml | oc delete -f -`

Screeshots:
Peek 2020-06-08 10-48
Peek 2020-06-08 10-57

### CODE REVIEW

**Comment by jelkosz** [comment]
@yaacov do you rely on the fact that the service account is already there and configured?

**Comment by yaacov** [comment]
> @yaacov do you rely on the fact that the service account is already there and configured?

yes

**Comment by jelkosz** [comment]
ok, this makes it a bit more complicated to use. We can either have one common namespace for all deployed envs which makes it a bit more complicated to clean up or a namespace per env but that than needs to be prepared beforehand. Anyway, the boost in usability is worth the effort to make the cleanup a bit more challenging, so merging.

thank you for the patch!

**Comment by yaacov** [comment]
p.s.

Didn't add in the description:

**how to use:**

**create**:
`oc process -p PATCH=5490 -f template.yaml | oc create -f -`

**delete:**
`oc process -p PATCH=5490 -f template.yaml | oc delete -f -`

**Pull request merged**
